import type { Country } from './types';

/** Source of truth for the quiz countries (ISO 3166-1 numeric ids). `level` is the easiest level that includes it. */
export const COUNTRIES: readonly Country[] = [
  { id: 4, name: 'Afeganistão', aliases: ['afeganistao', 'afghanistan'], level: 2 },
  { id: 8, name: 'Albânia', aliases: ['albania'], level: 3 },
  { id: 12, name: 'Argélia', aliases: ['argelia', 'algeria'], level: 2 },
  { id: 24, name: 'Angola', aliases: ['angola'], level: 2 },
  { id: 31, name: 'Azerbaijão', aliases: ['azerbaijao', 'azerbaijan'], level: 2 },
  { id: 32, name: 'Argentina', aliases: ['argentina'], level: 1 },
  { id: 36, name: 'Austrália', aliases: ['australia'], level: 1 },
  { id: 40, name: 'Áustria', aliases: ['austria'], level: 1 },
  { id: 50, name: 'Bangladesh', aliases: ['bangladesh'], level: 2 },
  { id: 51, name: 'Armênia', aliases: ['armenia'], level: 2 },
  { id: 56, name: 'Bélgica', aliases: ['belgica', 'belgium', 'belgique'], level: 1 },
  { id: 64, name: 'Butão', aliases: ['butao', 'bhutan'], level: 2 },
  { id: 68, name: 'Bolívia', aliases: ['bolivia'], level: 1 },
  {
    id: 70,
    name: 'Bósnia e Herzegovina',
    aliases: ['bosnia e herzegovina', 'bosnia and herzegovina', 'bosnia', 'bih'],
    level: 2,
  },
  { id: 72, name: 'Botsuana', aliases: ['botsuana', 'botswana'], level: 2 },
  { id: 76, name: 'Brasil', aliases: ['brasil', 'brazil'], level: 1 },
  { id: 84, name: 'Belize', aliases: ['belize'], level: 2 },
  { id: 100, name: 'Bulgária', aliases: ['bulgaria'], level: 2 },
  { id: 104, name: 'Mianmar', aliases: ['mianmar', 'myanmar', 'birmania', 'burma'], level: 2 },
  { id: 108, name: 'Burundi', aliases: ['burundi'], level: 3 },
  { id: 112, name: 'Bielorrússia', aliases: ['bielorrussia', 'belarus'], level: 2 },
  { id: 116, name: 'Camboja', aliases: ['camboja', 'cambodia'], level: 2 },
  { id: 120, name: 'Camarões', aliases: ['camaroes', 'cameroon', 'cameroun'], level: 2 },
  { id: 124, name: 'Canadá', aliases: ['canada'], level: 1 },
  {
    id: 140,
    name: 'Rep. Centro-Africana',
    aliases: ['republica centro-africana', 'republica centroafricana', 'central african republic', 'car', 'rca'],
    level: 2,
  },
  { id: 144, name: 'Sri Lanka', aliases: ['sri lanka', 'srilanka', 'ceilao'], level: 2 },
  { id: 148, name: 'Chade', aliases: ['chade', 'chad'], level: 2 },
  { id: 152, name: 'Chile', aliases: ['chile'], level: 1 },
  { id: 156, name: 'China', aliases: ['china', 'republica popular da china', 'república popular da china'], level: 1 },
  { id: 158, name: 'Taiwan', aliases: ['taiwan'], level: 2 },
  { id: 170, name: 'Colômbia', aliases: ['colombia'], level: 1 },
  {
    id: 178,
    name: 'Congo',
    aliases: ['congo', 'republica do congo', 'congo brazzaville', 'republic of the congo'],
    level: 3,
  },
  {
    id: 180,
    name: 'Rep. Dem. do Congo',
    aliases: [
      'republica democratica do congo',
      'rep dem do congo',
      'rdc',
      'congo democratico',
      'democratic republic of congo',
      'drc',
      'zaire',
      'congo dem',
    ],
    level: 2,
  },
  { id: 188, name: 'Costa Rica', aliases: ['costa rica', 'costarica'], level: 2 },
  { id: 191, name: 'Croácia', aliases: ['croacia', 'croatia'], level: 2 },
  { id: 192, name: 'Cuba', aliases: ['cuba'], level: 1 },
  { id: 196, name: 'Chipre', aliases: ['chipre', 'cyprus', 'nicosia', 'nicósia'], level: 3 },
  {
    id: 203,
    name: 'República Tcheca',
    aliases: ['republica tcheca', 'tcheca', 'czech republic', 'czechia', 'czech'],
    level: 2,
  },
  { id: 204, name: 'Benin', aliases: ['benin'], level: 2 },
  { id: 208, name: 'Dinamarca', aliases: ['dinamarca', 'denmark'], level: 1 },
  {
    id: 214,
    name: 'República Dominicana',
    aliases: ['republica dominicana', 'dominicana', 'dominican republic'],
    level: 2,
  },
  { id: 218, name: 'Equador', aliases: ['equador', 'ecuador'], level: 2 },
  { id: 222, name: 'El Salvador', aliases: ['el salvador', 'salvador'], level: 2 },
  { id: 226, name: 'Guiné Equatorial', aliases: ['guine equatorial', 'equatorial guinea'], level: 2 },
  { id: 231, name: 'Etiópia', aliases: ['etiopia', 'ethiopia'], level: 1 },
  { id: 232, name: 'Eritreia', aliases: ['eritreia', 'eritrea'], level: 2 },
  { id: 233, name: 'Estônia', aliases: ['estonia', 'estonia'], level: 2 },
  { id: 242, name: 'Fiji', aliases: ['fiji'], level: 3 },
  { id: 246, name: 'Finlândia', aliases: ['finlandia', 'finland', 'suomi'], level: 2 },
  { id: 250, name: 'França', aliases: ['franca', 'france'], level: 1 },
  { id: 254, name: 'Guiana Francesa', aliases: ['guiana francesa', 'french guiana', 'guyana francesa'], level: 3 },
  { id: 262, name: 'Djibuti', aliases: ['djibuti', 'djibouti'], level: 2 },
  { id: 266, name: 'Gabão', aliases: ['gabao', 'gabon'], level: 2 },
  { id: 268, name: 'Geórgia', aliases: ['georgia'], level: 2 },
  { id: 276, name: 'Alemanha', aliases: ['alemanha', 'germany', 'deutschland'], level: 1 },
  { id: 288, name: 'Gana', aliases: ['gana', 'ghana'], level: 2 },
  { id: 300, name: 'Grécia', aliases: ['grecia', 'greece'], level: 1 },
  { id: 304, name: 'Groenlândia', aliases: ['groenlandia', 'greenland'], level: 2 },
  { id: 320, name: 'Guatemala', aliases: ['guatemala'], level: 2 },
  { id: 324, name: 'Guiné', aliases: ['guine', 'guinea', 'guine conacri', 'guine-conacri'], level: 2 },
  { id: 328, name: 'Guiana', aliases: ['guiana', 'guyana', 'guiana inglesa'], level: 2 },
  { id: 332, name: 'Haiti', aliases: ['haiti'], level: 2 },
  { id: 340, name: 'Honduras', aliases: ['honduras'], level: 2 },
  { id: 348, name: 'Hungria', aliases: ['hungria', 'hungary'], level: 1 },
  { id: 352, name: 'Islândia', aliases: ['islandia', 'iceland'], level: 2 },
  { id: 356, name: 'Índia', aliases: ['india'], level: 1 },
  { id: 360, name: 'Indonésia', aliases: ['indonesia'], level: 1 },
  { id: 364, name: 'Irã', aliases: ['ira', 'iran'], level: 1 },
  { id: 368, name: 'Iraque', aliases: ['iraque', 'iraq'], level: 1 },
  { id: 372, name: 'Irlanda', aliases: ['irlanda', 'ireland', 'eire'], level: 2 },
  { id: 376, name: 'Israel', aliases: ['israel'], level: 1 },
  { id: 380, name: 'Itália', aliases: ['italia', 'italy'], level: 1 },
  { id: 383, name: 'Kosovo', aliases: ['kosovo'], level: 2 },
  {
    id: 384,
    name: 'Costa do Marfim',
    aliases: ['costa do marfim', 'cote d ivoire', 'ivory coast', 'costa de marfim'],
    level: 2,
  },
  { id: 388, name: 'Jamaica', aliases: ['jamaica'], level: 3 },
  { id: 392, name: 'Japão', aliases: ['japao', 'japan'], level: 1 },
  { id: 398, name: 'Cazaquistão', aliases: ['cazaquistao', 'kazakhstan'], level: 2 },
  { id: 400, name: 'Jordânia', aliases: ['jordania', 'jordan'], level: 2 },
  { id: 404, name: 'Quênia', aliases: ['quenia', 'kenya'], level: 1 },
  { id: 408, name: 'Coreia do Norte', aliases: ['coreia do norte', 'norte coreia', 'north korea', 'dprk'], level: 2 },
  { id: 410, name: 'Coreia do Sul', aliases: ['coreia do sul', 'sul coreia', 'south korea', 'coreia'], level: 1 },
  { id: 414, name: 'Kuwait', aliases: ['kuwait'], level: 2 },
  { id: 417, name: 'Quirguistão', aliases: ['quirguistao', 'kyrgyzstan', 'quirguizia'], level: 2 },
  { id: 418, name: 'Laos', aliases: ['laos'], level: 2 },
  { id: 422, name: 'Líbano', aliases: ['libano', 'lebanon'], level: 2 },
  { id: 426, name: 'Lesoto', aliases: ['lesoto', 'lesotho'], level: 3 },
  { id: 428, name: 'Letônia', aliases: ['letonia', 'latvia'], level: 2 },
  { id: 430, name: 'Libéria', aliases: ['liberia'], level: 2 },
  { id: 434, name: 'Líbia', aliases: ['libia', 'libya'], level: 2 },
  { id: 440, name: 'Lituânia', aliases: ['lituania', 'lithuania'], level: 2 },
  { id: 442, name: 'Luxemburgo', aliases: ['luxemburgo', 'luxembourg'], level: 3 },
  { id: 450, name: 'Madagáscar', aliases: ['madagascar', 'madagasca', 'madagaskar'], level: 2 },
  { id: 454, name: 'Malaui', aliases: ['malaui', 'malawi'], level: 2 },
  { id: 458, name: 'Malásia', aliases: ['malasia', 'malaysia'], level: 1 },
  { id: 466, name: 'Mali', aliases: ['mali'], level: 2 },
  { id: 478, name: 'Mauritânia', aliases: ['mauritania'], level: 2 },
  { id: 484, name: 'México', aliases: ['mexico'], level: 1 },
  { id: 496, name: 'Mongólia', aliases: ['mongolia'], level: 2 },
  { id: 498, name: 'Moldávia', aliases: ['moldavia', 'moldova'], level: 2 },
  { id: 499, name: 'Montenegro', aliases: ['montenegro'], level: 2 },
  { id: 504, name: 'Marrocos', aliases: ['marrocos', 'morocco'], level: 1 },
  { id: 508, name: 'Moçambique', aliases: ['mocambique', 'mozambique'], level: 2 },
  { id: 512, name: 'Omã', aliases: ['oma', 'oman'], level: 2 },
  { id: 516, name: 'Namíbia', aliases: ['namibia'], level: 2 },
  { id: 524, name: 'Nepal', aliases: ['nepal'], level: 2 },
  { id: 528, name: 'Países Baixos', aliases: ['paises baixos', 'holanda', 'netherlands', 'holland'], level: 1 },
  { id: 554, name: 'Nova Zelândia', aliases: ['nova zelandia', 'new zealand'], level: 2 },
  { id: 558, name: 'Nicarágua', aliases: ['nicaragua'], level: 2 },
  { id: 562, name: 'Níger', aliases: ['niger'], level: 2 },
  { id: 566, name: 'Nigéria', aliases: ['nigeria'], level: 1 },
  { id: 578, name: 'Noruega', aliases: ['noruega', 'norway', 'norge'], level: 2 },
  { id: 586, name: 'Paquistão', aliases: ['paquistao', 'pakistan'], level: 1 },
  { id: 591, name: 'Panamá', aliases: ['panama'], level: 2 },
  { id: 598, name: 'Papua Nova Guiné', aliases: ['papua nova guine', 'papua new guinea', 'png'], level: 3 },
  { id: 600, name: 'Paraguai', aliases: ['paraguai', 'paraguay'], level: 2 },
  { id: 604, name: 'Peru', aliases: ['peru'], level: 1 },
  { id: 608, name: 'Filipinas', aliases: ['filipinas', 'philippines'], level: 2 },
  { id: 616, name: 'Polônia', aliases: ['polonia', 'poland', 'polska'], level: 1 },
  { id: 620, name: 'Portugal', aliases: ['portugal'], level: 1 },
  {
    id: 624,
    name: 'Guiné-Bissau',
    aliases: ['guine-bissau', 'guine bissau', 'guinea-bissau', 'guinea bissau'],
    level: 3,
  },
  { id: 626, name: 'Timor-Leste', aliases: ['timor-leste', 'timor leste', 'timor', 'east timor'], level: 2 },
  { id: 634, name: 'Catar', aliases: ['catar', 'qatar'], level: 2 },
  { id: 642, name: 'Romênia', aliases: ['romenia', 'romania'], level: 2 },
  { id: 643, name: 'Rússia', aliases: ['russia'], level: 1 },
  { id: 646, name: 'Ruanda', aliases: ['ruanda', 'rwanda'], level: 2 },
  { id: 682, name: 'Arábia Saudita', aliases: ['arabia saudita', 'saudi arabia', 'arabia'], level: 1 },
  { id: 686, name: 'Senegal', aliases: ['senegal'], level: 2 },
  { id: 688, name: 'Sérvia', aliases: ['servia', 'serbia'], level: 2 },
  { id: 694, name: 'Serra Leoa', aliases: ['serra leoa', 'sierra leone'], level: 2 },
  { id: 703, name: 'Eslováquia', aliases: ['eslovaquia', 'slovakia'], level: 2 },
  { id: 704, name: 'Vietnã', aliases: ['vietna', 'vietnam', 'viet nam'], level: 2 },
  { id: 705, name: 'Eslovênia', aliases: ['eslovenia', 'slovenia'], level: 2 },
  { id: 706, name: 'Somália', aliases: ['somalia'], level: 2 },
  { id: 710, name: 'África do Sul', aliases: ['africa do sul', 'south africa'], level: 1 },
  { id: 716, name: 'Zimbábue', aliases: ['zimbabue', 'zimbabwe'], level: 2 },
  { id: 724, name: 'Espanha', aliases: ['espanha', 'spain'], level: 1 },
  { id: 728, name: 'Sudão do Sul', aliases: ['sudao do sul', 'south sudan'], level: 2 },
  { id: 729, name: 'Sudão', aliases: ['sudao', 'sudan'], level: 2 },
  { id: 740, name: 'Suriname', aliases: ['suriname', 'surinam'], level: 2 },
  { id: 748, name: 'Eswatini', aliases: ['eswatini', 'suazilandia', 'swaziland'], level: 3 },
  { id: 752, name: 'Suécia', aliases: ['suecia', 'sweden', 'sverige'], level: 1 },
  { id: 756, name: 'Suíça', aliases: ['suica', 'switzerland', 'suisse'], level: 1 },
  { id: 760, name: 'Síria', aliases: ['siria', 'syria'], level: 2 },
  { id: 762, name: 'Tajiquistão', aliases: ['tajiquistao', 'tajikistan'], level: 2 },
  { id: 764, name: 'Tailândia', aliases: ['tailandia', 'thailand'], level: 1 },
  { id: 768, name: 'Togo', aliases: ['togo'], level: 2 },
  { id: 780, name: 'Trinidad e Tobago', aliases: ['trinidad e tobago', 'trinidad and tobago', 'trinidad'], level: 3 },
  { id: 784, name: 'Emirados Árabes Unidos', aliases: ['emirados arabes unidos', 'uae', 'emirates', 'eau'], level: 1 },
  { id: 788, name: 'Tunísia', aliases: ['tunisia'], level: 2 },
  { id: 792, name: 'Turquia', aliases: ['turquia', 'turkey', 'turkiye'], level: 1 },
  { id: 795, name: 'Turcomenistão', aliases: ['turcomenistao', 'turkmenistan'], level: 2 },
  { id: 800, name: 'Uganda', aliases: ['uganda'], level: 1 },
  { id: 804, name: 'Ucrânia', aliases: ['ucrania', 'ukraine'], level: 3 },
  {
    id: 807,
    name: 'Macedônia do Norte',
    aliases: ['macedonia do norte', 'north macedonia', 'macedonia', 'makedonia'],
    level: 2,
  },
  { id: 818, name: 'Egito', aliases: ['egito', 'egypt'], level: 1 },
  {
    id: 826,
    name: 'Reino Unido',
    aliases: ['reino unido', 'united kingdom', 'uk', 'gra-bretanha', 'great britain', 'inglaterra'],
    level: 1,
  },
  { id: 834, name: 'Tanzânia', aliases: ['tanzania'], level: 2 },
  {
    id: 840,
    name: 'Estados Unidos',
    aliases: ['estados unidos', 'usa', 'eua', 'united states', 'america', 'estados unidos da america'],
    level: 1,
  },
  { id: 854, name: 'Burkina Faso', aliases: ['burkina faso', 'burkina'], level: 2 },
  { id: 858, name: 'Uruguai', aliases: ['uruguai', 'uruguay'], level: 1 },
  { id: 860, name: 'Uzbequistão', aliases: ['uzbequistao', 'uzbekistan'], level: 2 },
  { id: 862, name: 'Venezuela', aliases: ['venezuela'], level: 1 },
  { id: 887, name: 'Iêmen', aliases: ['iemen', 'yemen'], level: 2 },
  { id: 894, name: 'Zâmbia', aliases: ['zambia'], level: 2 },
];
