const DB = {
  4:   { pt:"Afeganistão",               a:["afeganistao","afghanistan"] },
  8:   { pt:"Albânia",                   a:["albania"] },
  12:  { pt:"Argélia",                   a:["argelia","algeria"] },
  24:  { pt:"Angola",                    a:["angola"] },
  31:  { pt:"Azerbaijão",                a:["azerbaijao","azerbaijan"] },
  32:  { pt:"Argentina",                 a:["argentina"] },
  36:  { pt:"Austrália",                 a:["australia"] },
  40:  { pt:"Áustria",                   a:["austria"] },
  50:  { pt:"Bangladesh",                a:["bangladesh"] },
  51:  { pt:"Armênia",                   a:["armenia"] },
  56:  { pt:"Bélgica",                   a:["belgica","belgium","belgique"] },
  64:  { pt:"Butão",                     a:["butao","bhutan"] },
  68:  { pt:"Bolívia",                   a:["bolivia"] },
  70:  { pt:"Bósnia e Herzegovina",      a:["bosnia e herzegovina","bosnia and herzegovina","bosnia","bih"] },
  72:  { pt:"Botsuana",                  a:["botsuana","botswana"] },
  76:  { pt:"Brasil",                    a:["brasil","brazil"] },
  100: { pt:"Bulgária",                  a:["bulgaria"] },
  104: { pt:"Mianmar",                   a:["mianmar","myanmar","birmania","burma"] },
  112: { pt:"Bielorrússia",              a:["bielorrussia","belarus"] },
  116: { pt:"Camboja",                   a:["camboja","cambodia"] },
  120: { pt:"Camarões",                  a:["camaroes","cameroon","cameroun"] },
  124: { pt:"Canadá",                    a:["canada"] },
  140: { pt:"Rep. Centro-Africana",      a:["republica centro-africana","republica centroafricana","central african republic","car","rca"] },
  144: { pt:"Sri Lanka",                 a:["sri lanka","srilanka","ceilao"] },
  148: { pt:"Chade",                     a:["chade","chad"] },
  152: { pt:"Chile",                     a:["chile"] },
  156: { pt:"China",                     a:["china","republica popular da china","república popular da china"] },
  170: { pt:"Colômbia",                  a:["colombia"] },
  178: { pt:"Congo",                     a:["congo","republica do congo","congo brazzaville","republic of the congo"] },
  180: { pt:"Rep. Dem. do Congo",        a:["republica democratica do congo","rep dem do congo","rdc","congo democratico","democratic republic of congo","drc","zaire","congo dem"] },
  188: { pt:"Costa Rica",                a:["costa rica","costarica"] },
  191: { pt:"Croácia",                   a:["croacia","croatia"] },
  192: { pt:"Cuba",                      a:["cuba"] },
  196: { pt:"Chipre",                    a:["chipre","cyprus","nicosia","nicósia"] },
  233: { pt:"Estônia",                   a:["estonia","estonia"] },
  203: { pt:"República Tcheca",          a:["republica tcheca","tcheca","czech republic","czechia","czech"] },
  204: { pt:"Benin",                     a:["benin"] },
  208: { pt:"Dinamarca",                 a:["dinamarca","denmark"] },
  214: { pt:"República Dominicana",      a:["republica dominicana","dominicana","dominican republic"] },
  218: { pt:"Equador",                   a:["equador","ecuador"] },
  231: { pt:"Etiópia",                   a:["etiopia","ethiopia"] },
  232: { pt:"Eritreia",                  a:["eritreia","eritrea"] },
  246: { pt:"Finlândia",                 a:["finlandia","finland","suomi"] },
  250: { pt:"França",                    a:["franca","france"] },
  266: { pt:"Gabão",                     a:["gabao","gabon"] },
  268: { pt:"Geórgia",                   a:["georgia"] },
  276: { pt:"Alemanha",                  a:["alemanha","germany","deutschland"] },
  288: { pt:"Gana",                      a:["gana","ghana"] },
  300: { pt:"Grécia",                    a:["grecia","greece"] },
  320: { pt:"Guatemala",                 a:["guatemala"] },
  324: { pt:"Guiné",                     a:["guine","guinea","guine conacri","guine-conacri"] },
  328: { pt:"Guiana",                    a:["guiana","guyana","guiana inglesa"] },
  332: { pt:"Haiti",                     a:["haiti"] },
  340: { pt:"Honduras",                  a:["honduras"] },
  348: { pt:"Hungria",                   a:["hungria","hungary"] },
  352: { pt:"Islândia",                  a:["islandia","iceland"] },
  356: { pt:"Índia",                     a:["india"] },
  360: { pt:"Indonésia",                 a:["indonesia"] },
  364: { pt:"Irã",                       a:["ira","iran"] },
  368: { pt:"Iraque",                    a:["iraque","iraq"] },
  372: { pt:"Irlanda",                   a:["irlanda","ireland","eire"] },
  376: { pt:"Israel",                    a:["israel"] },
  380: { pt:"Itália",                    a:["italia","italy"] },
  384: { pt:"Costa do Marfim",           a:["costa do marfim","cote d ivoire","ivory coast","costa de marfim"] },
  388: { pt:"Jamaica",                   a:["jamaica"] },
  392: { pt:"Japão",                     a:["japao","japan"] },
  398: { pt:"Cazaquistão",               a:["cazaquistao","kazakhstan"] },
  400: { pt:"Jordânia",                  a:["jordania","jordan"] },
  404: { pt:"Quênia",                    a:["quenia","kenya"] },
  408: { pt:"Coreia do Norte",           a:["coreia do norte","norte coreia","north korea","dprk"] },
  410: { pt:"Coreia do Sul",             a:["coreia do sul","sul coreia","south korea","coreia"] },
  418: { pt:"Laos",                      a:["laos"] },
  422: { pt:"Líbano",                    a:["libano","lebanon"] },
  428: { pt:"Letônia",                   a:["letonia","latvia"] },
  430: { pt:"Libéria",                   a:["liberia"] },
  434: { pt:"Líbia",                     a:["libia","libya"] },
  440: { pt:"Lituânia",                  a:["lituania","lithuania"] },
  442: { pt:"Luxemburgo",                a:["luxemburgo","luxembourg"] },
  454: { pt:"Malaui",                    a:["malaui","malawi"] },
  458: { pt:"Malásia",                   a:["malasia","malaysia"] },
  466: { pt:"Mali",                      a:["mali"] },
  478: { pt:"Mauritânia",                a:["mauritania"] },
  484: { pt:"México",                    a:["mexico"] },
  496: { pt:"Mongólia",                  a:["mongolia"] },
  498: { pt:"Moldávia",                  a:["moldavia","moldova"] },
  499: { pt:"Montenegro",                a:["montenegro"] },
  504: { pt:"Marrocos",                  a:["marrocos","morocco"] },
  508: { pt:"Moçambique",                a:["mocambique","mozambique"] },
  516: { pt:"Namíbia",                   a:["namibia"] },
  524: { pt:"Nepal",                     a:["nepal"] },
  528: { pt:"Países Baixos",             a:["paises baixos","holanda","netherlands","holland"] },
  558: { pt:"Nicarágua",                 a:["nicaragua"] },
  562: { pt:"Níger",                     a:["niger"] },
  566: { pt:"Nigéria",                   a:["nigeria"] },
  578: { pt:"Noruega",                   a:["noruega","norway","norge"] },
  586: { pt:"Paquistão",                 a:["paquistao","pakistan"] },
  591: { pt:"Panamá",                    a:["panama"] },
  598: { pt:"Papua Nova Guiné",          a:["papua nova guine","papua new guinea","png"] },
  600: { pt:"Paraguai",                  a:["paraguai","paraguay"] },
  604: { pt:"Peru",                      a:["peru"] },
  608: { pt:"Filipinas",                 a:["filipinas","philippines"] },
  616: { pt:"Polônia",                   a:["polonia","poland","polska"] },
  620: { pt:"Portugal",                  a:["portugal"] },
  642: { pt:"Romênia",                   a:["romenia","romania"] },
  643: { pt:"Rússia",                    a:["russia"] },
  646: { pt:"Ruanda",                    a:["ruanda","rwanda"] },
  682: { pt:"Arábia Saudita",            a:["arabia saudita","saudi arabia","arabia"] },
  686: { pt:"Senegal",                   a:["senegal"] },
  688: { pt:"Sérvia",                    a:["servia","serbia"] },
  694: { pt:"Serra Leoa",                a:["serra leoa","sierra leone"] },
  703: { pt:"Eslováquia",                a:["eslovaquia","slovakia"] },
  705: { pt:"Eslovênia",                 a:["eslovenia","slovenia"] },
  706: { pt:"Somália",                   a:["somalia"] },
  704: { pt:"Vietnã",                    a:["vietna","vietnam","viet nam"] },
  710: { pt:"África do Sul",             a:["africa do sul","south africa"] },
  716: { pt:"Zimbábue",                  a:["zimbabue","zimbabwe"] },
  724: { pt:"Espanha",                   a:["espanha","spain"] },
  729: { pt:"Sudão",                     a:["sudao","sudan"] },
  740: { pt:"Suriname",                  a:["suriname","surinam"] },
  748: { pt:"Eswatini",                  a:["eswatini","suazilandia","swaziland"] },
  752: { pt:"Suécia",                    a:["suecia","sweden","sverige"] },
  756: { pt:"Suíça",                     a:["suica","switzerland","suisse"] },
  760: { pt:"Síria",                     a:["siria","syria"] },
  762: { pt:"Tajiquistão",               a:["tajiquistao","tajikistan"] },
  764: { pt:"Tailândia",                 a:["tailandia","thailand"] },
  768: { pt:"Togo",                      a:["togo"] },
  780: { pt:"Trinidad e Tobago",         a:["trinidad e tobago","trinidad and tobago","trinidad"] },
  784: { pt:"Emirados Árabes Unidos",    a:["emirados arabes unidos","uae","emirates","eau"] },
  788: { pt:"Tunísia",                   a:["tunisia"] },
  792: { pt:"Turquia",                   a:["turquia","turkey","turkiye"] },
  800: { pt:"Uganda",                    a:["uganda"] },
  804: { pt:"Ucrânia",                   a:["ucrania","ukraine"] },
  807: { pt:"Macedônia do Norte",        a:["macedonia do norte","north macedonia","macedonia","makedonia"] },
  818: { pt:"Egito",                     a:["egito","egypt"] },
  826: { pt:"Reino Unido",               a:["reino unido","united kingdom","uk","gra-bretanha","great britain","inglaterra"] },
  840: { pt:"Estados Unidos",            a:["estados unidos","usa","eua","united states","america","estados unidos da america"] },
  858: { pt:"Uruguai",                   a:["uruguai","uruguay"] },
  860: { pt:"Uzbequistão",               a:["uzbequistao","uzbekistan"] },
  862: { pt:"Venezuela",                 a:["venezuela"] },
  887: { pt:"Iêmen",                     a:["iemen","yemen"] },
  894: { pt:"Zâmbia",                    a:["zambia"] },
  304: { pt:"Groenlândia",               a:["groenlandia","greenland"] },
  383: { pt:"Kosovo",                    a:["kosovo"] },
  84:  { pt:"Belize",                    a:["belize"] },
  108: { pt:"Burundi",                   a:["burundi"] },
  158: { pt:"Taiwan",                    a:["taiwan"] },
  222: { pt:"El Salvador",               a:["el salvador","salvador"] },
  226: { pt:"Guiné Equatorial",          a:["guine equatorial","equatorial guinea"] },
  242: { pt:"Fiji",                      a:["fiji"] },
  262: { pt:"Djibuti",                   a:["djibuti","djibouti"] },
  414: { pt:"Kuwait",                    a:["kuwait"] },
  417: { pt:"Quirguistão",               a:["quirguistao","kyrgyzstan","quirguizia"] },
  426: { pt:"Lesoto",                    a:["lesoto","lesotho"] },
  450: { pt:"Madagáscar",                a:["madagascar","madagasca","madagaskar"] },
  512: { pt:"Omã",                       a:["oma","oman"] },
  554: { pt:"Nova Zelândia",             a:["nova zelandia","new zealand"] },
  624: { pt:"Guiné-Bissau",              a:["guine-bissau","guine bissau","guinea-bissau","guinea bissau"] },
  626: { pt:"Timor-Leste",               a:["timor-leste","timor leste","timor","east timor"] },
  634: { pt:"Catar",                     a:["catar","qatar"] },
  728: { pt:"Sudão do Sul",              a:["sudao do sul","south sudan"] },
  795: { pt:"Turcomenistão",             a:["turcomenistao","turkmenistan"] },
  834: { pt:"Tanzânia",                  a:["tanzania"] },
  854: { pt:"Burkina Faso",              a:["burkina faso","burkina"] },
  254: { pt:"Guiana Francesa",           a:["guiana francesa","french guiana","guyana francesa"] },
};
